[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = ["python3 -c 'print(\"Build completed\")'"]

[start]
cmd = "python3 app.py"

