[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "python backend/start.py"

